FROM alpine:3.9.5
ARG AWS_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ENV HOME /tmp

RUN apk --no-cache \
    add python py-pip py-setuptools git ca-certificates && \
    pip install python-dateutil==2.8.1

RUN git clone --branch VERSION https://github.com/s3tools/s3cmd.git /opt/s3cmd
RUN ln -s /opt/s3cmd/s3cmd /usr/bin/s3cmd

WORKDIR /tmp
